import type { Answer, Category, Domain, Question } from "./domain";

export const JAVA_BACKEND_DOMAIN: Domain = {
  slug: "java_backend",
  name: "Java 后端",
  description: "第一版聚焦 Java 后端面试复习，后续可扩展为其他技术方向。",
  firstVersionFocus: true,
};

export const JAVA_BACKEND_CATEGORIES: Category[] = [
  {
    slug: "java-language",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    name: "Java 语言基础",
    description: "语法、面向对象、异常、泛型、反射等基础能力。",
    order: 0,
  },
  {
    slug: "jvm",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    name: "JVM",
    description: "内存模型、类加载、GC、调优和线上问题排查。",
    order: 1,
  },
  {
    slug: "java-collections",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    name: "Java 集合",
    description: "List、Map、Set、HashMap、ConcurrentHashMap 等集合高频题。",
    order: 2,
  },
  {
    slug: "java-concurrency",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    name: "Java 并发",
    description: "线程池、锁、CAS、AQS、volatile、并发容器和实践场景。",
    order: 3,
  },
  {
    slug: "spring-boot",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    name: "Spring 与 Spring Boot",
    description: "IoC、AOP、事务、自动配置、Bean 生命周期和常见工程问题。",
    order: 4,
  },
  {
    slug: "orm",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    name: "MyBatis / JPA 基础",
    description: "ORM、SQL 映射、懒加载、缓存和动态 SQL。",
    order: 5,
  },
  {
    slug: "mysql",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    name: "MySQL",
    description: "索引、事务、锁、MVCC、SQL 优化和慢查询排查。",
    order: 6,
  },
  {
    slug: "redis",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    name: "Redis",
    description: "缓存、分布式锁、持久化、过期策略、缓存击穿和雪崩。",
    order: 7,
  },
  {
    slug: "message-queue",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    name: "消息队列",
    description: "异步解耦、削峰、可靠投递、顺序消息和重复消费。",
    order: 8,
  },
  {
    slug: "distributed-systems",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    name: "分布式系统",
    description: "一致性、幂等、分布式事务、限流、熔断和服务治理。",
    order: 9,
  },
  {
    slug: "system-design",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    name: "系统设计",
    description: "架构拆分、容量估算、高可用、可扩展性和性能瓶颈。",
    order: 10,
  },
  {
    slug: "project-deep-dive",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    name: "项目经历追问",
    description: "围绕简历项目进行架构、选型、问题排查和优化追问。",
    order: 11,
  },
  {
    slug: "behavioral",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    name: "工程师行为面试题",
    description: "协作、冲突处理、复盘、主动性和工程判断。",
    order: 12,
  },
];

export const JAVA_BACKEND_SEED_QUESTIONS: Question[] = [
  {
    id: "q_java_object_equals_hashcode",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    categorySlug: "java-language",
    type: "concept",
    difficulty: "easy",
    title: "equals 和 hashCode 为什么要同时重写？",
    content: "请说明 equals 与 hashCode 的契约，以及它们在 HashMap、HashSet 中的影响。",
    tags: ["equals", "hashCode", "集合"],
    sourceType: "seed",
    aiGenerated: false,
  },
  {
    id: "q_jvm_gc_roots",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    categorySlug: "jvm",
    type: "concept",
    difficulty: "medium",
    title: "什么是 GC Roots？",
    content: "请解释 GC Roots 的作用，并说明哪些对象可以作为 GC Roots。",
    tags: ["JVM", "GC"],
    sourceType: "seed",
    aiGenerated: false,
  },
  {
    id: "q_hashmap_resize",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    categorySlug: "java-collections",
    type: "concept",
    difficulty: "medium",
    title: "HashMap 扩容机制",
    content: "HashMap 为什么需要扩容？扩容过程中有什么风险？",
    tags: ["HashMap", "集合"],
    sourceType: "seed",
    aiGenerated: false,
  },
  {
    id: "q_thread_pool_rejection",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    categorySlug: "java-concurrency",
    type: "scenario",
    difficulty: "medium",
    title: "线程池拒绝策略怎么选？",
    content: "线上接口使用线程池处理异步任务，如果队列满了，你会如何选择拒绝策略？",
    tags: ["线程池", "拒绝策略", "并发"],
    sourceType: "seed",
    aiGenerated: false,
  },
  {
    id: "q_spring_transaction_failure",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    categorySlug: "spring-boot",
    type: "scenario",
    difficulty: "medium",
    title: "Spring 事务为什么会失效？",
    content: "请列举常见 Spring 事务失效场景，并说明如何定位。",
    tags: ["Spring", "事务", "AOP"],
    sourceType: "seed",
    aiGenerated: false,
  },
  {
    id: "q_mysql_index_left_prefix",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    categorySlug: "mysql",
    type: "concept",
    difficulty: "medium",
    title: "联合索引最左前缀原则",
    content: "什么是联合索引最左前缀原则？哪些查询会导致索引失效？",
    tags: ["MySQL", "索引"],
    sourceType: "seed",
    aiGenerated: false,
  },
  {
    id: "q_redis_cache_breakdown",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    categorySlug: "redis",
    type: "scenario",
    difficulty: "medium",
    title: "如何处理缓存击穿？",
    content: "热点 key 过期导致大量请求打到数据库，你会如何设计防护方案？",
    tags: ["Redis", "缓存击穿"],
    sourceType: "seed",
    aiGenerated: false,
  },
  {
    id: "q_mq_duplicate_consumption",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    categorySlug: "message-queue",
    type: "scenario",
    difficulty: "hard",
    title: "消息重复消费如何处理？",
    content: "如果 MQ 消费端收到重复消息，你如何保证业务幂等？",
    tags: ["MQ", "幂等", "重复消费"],
    sourceType: "seed",
    aiGenerated: false,
  },
  {
    id: "q_project_latency_optimization",
    domainSlug: JAVA_BACKEND_DOMAIN.slug,
    categorySlug: "project-deep-dive",
    type: "project_deep_dive",
    difficulty: "hard",
    title: "你项目里做过哪些性能优化？",
    content: "请结合项目经历说明一次接口性能优化，包含定位、方案、结果和取舍。",
    tags: ["项目经历", "性能优化", "追问"],
    sourceType: "seed",
    aiGenerated: false,
  },
];

export const JAVA_BACKEND_SEED_ANSWERS: Answer[] = [
  {
    id: "a_java_object_equals_hashcode_standard",
    questionId: "q_java_object_equals_hashcode",
    answerType: "standard",
    status: "approved",
    content:
      "equals 用来判断两个对象在业务语义上是否相等，hashCode 用来支持哈希容器快速定位桶位。两者必须满足相等对象拥有相同 hashCode 的契约，否则 HashMap、HashSet 可能出现查不到、重复存储等问题。回答时还要说明自反性、对称性、传递性、一致性，以及重写时优先使用不可变或稳定字段。",
    keyPoints: ["业务语义相等", "相同 hashCode", "HashMap", "HashSet", "自反性"],
    model: "manual-seed",
    promptVersion: "seed-v1",
    tokenUsage: 0,
  },
  {
    id: "a_jvm_gc_roots_standard",
    questionId: "q_jvm_gc_roots",
    answerType: "standard",
    status: "approved",
    content:
      "GC Roots 是可达性分析的起点。JVM 从这些根对象出发沿引用链查找可达对象，不可达对象才可能被回收。常见 GC Roots 包括虚拟机栈中的局部变量引用、方法区中的静态变量引用、常量引用、JNI 引用以及被同步锁持有的对象。",
    keyPoints: ["可达性分析", "虚拟机栈引用", "静态变量", "常量引用", "JNI 引用"],
    model: "manual-seed",
    promptVersion: "seed-v1",
    tokenUsage: 0,
  },
  {
    id: "a_hashmap_resize_standard",
    questionId: "q_hashmap_resize",
    answerType: "standard",
    status: "approved",
    content:
      "HashMap 在元素数量超过容量与负载因子乘积时触发扩容。扩容会创建更大的数组，并根据 hash 和旧容量关系把节点迁移到新桶。面试时要说明负载因子、阈值、链表树化、JDK 1.8 的迁移优化，以及并发修改 HashMap 可能带来的数据不一致风险。",
    keyPoints: ["负载因子", "扩容阈值", "桶迁移", "链表树化", "并发风险"],
    model: "manual-seed",
    promptVersion: "seed-v1",
    tokenUsage: 0,
  },
  {
    id: "a_thread_pool_rejection_standard",
    questionId: "q_thread_pool_rejection",
    answerType: "standard",
    status: "approved",
    content:
      "线程池拒绝策略要结合任务重要性、调用链和降级能力选择。AbortPolicy 适合快速失败，CallerRunsPolicy 可反压调用方，DiscardPolicy 和 DiscardOldestPolicy 只适合可丢弃任务。线上还需要监控队列长度、拒绝次数，配合限流、降级、扩容和告警，避免把压力继续放大。",
    keyPoints: ["任务重要性", "AbortPolicy", "CallerRunsPolicy", "限流", "降级"],
    model: "manual-seed",
    promptVersion: "seed-v1",
    tokenUsage: 0,
  },
  {
    id: "a_spring_transaction_failure_standard",
    questionId: "q_spring_transaction_failure",
    answerType: "standard",
    status: "approved",
    content:
      "Spring 事务失效常见原因包括同类内部方法调用绕过代理、方法不是 public、异常被捕获未抛出、抛出非默认回滚异常、事务传播行为配置错误、数据库引擎不支持事务。定位时要确认代理是否生效、事务边界、异常类型、连接和日志。",
    keyPoints: ["代理", "内部方法调用", "异常被捕获", "传播行为", "事务边界"],
    model: "manual-seed",
    promptVersion: "seed-v1",
    tokenUsage: 0,
  },
  {
    id: "a_mysql_index_left_prefix_standard",
    questionId: "q_mysql_index_left_prefix",
    answerType: "standard",
    status: "approved",
    content:
      "联合索引按定义顺序构建，查询需要从最左列开始连续命中。跳过最左列、在索引列上使用函数或隐式类型转换、前置通配 like、范围查询后继续使用后续列，都可能降低索引利用率。回答时最好结合 explain 看 type、key、rows 和 Extra。",
    keyPoints: ["联合索引", "最左列", "连续命中", "范围查询", "explain"],
    model: "manual-seed",
    promptVersion: "seed-v1",
    tokenUsage: 0,
  },
  {
    id: "a_redis_cache_breakdown_standard",
    questionId: "q_redis_cache_breakdown",
    answerType: "standard",
    status: "approved",
    content:
      "缓存击穿是热点 key 失效后大量请求同时打到数据库。常用方案包括互斥锁或 singleflight 控制回源、逻辑过期异步刷新、热点 key 提前续期、限流降级，以及对空值和异常回源设置保护。还要结合监控确认热点、命中率和数据库压力。",
    keyPoints: ["热点 key", "互斥锁", "逻辑过期", "限流降级", "命中率"],
    model: "manual-seed",
    promptVersion: "seed-v1",
    tokenUsage: 0,
  },
  {
    id: "a_mq_duplicate_consumption_standard",
    questionId: "q_mq_duplicate_consumption",
    answerType: "standard",
    status: "approved",
    content:
      "消息重复消费通常通过业务幂等保证结果正确。可以使用业务唯一键、去重表、状态机、乐观锁或 Redis setnx 控制重复执行。还要说明消费确认时机、失败重试、事务一致性，以及重复消息不会导致库存、余额、积分等状态被重复变更。",
    keyPoints: ["业务幂等", "业务唯一键", "去重表", "状态机", "失败重试"],
    model: "manual-seed",
    promptVersion: "seed-v1",
    tokenUsage: 0,
  },
  {
    id: "a_project_latency_optimization_standard",
    questionId: "q_project_latency_optimization",
    answerType: "interview_style",
    status: "approved",
    content:
      "项目性能优化要讲成闭环：先描述业务背景和指标，再说明如何通过日志、链路追踪、慢 SQL、压测或火焰图定位瓶颈；接着讲具体方案，例如索引优化、缓存、批量处理、异步化、连接池调优；最后给出量化结果和取舍，例如 P95 降低、吞吐提升、成本或一致性影响。",
    keyPoints: ["业务背景", "定位瓶颈", "具体方案", "量化结果", "取舍"],
    model: "manual-seed",
    promptVersion: "seed-v1",
    tokenUsage: 0,
  },
];

export function getJavaBackendCatalog() {
  return {
    domain: JAVA_BACKEND_DOMAIN,
    categories: JAVA_BACKEND_CATEGORIES,
    questions: JAVA_BACKEND_SEED_QUESTIONS,
    answers: JAVA_BACKEND_SEED_ANSWERS,
  };
}
